version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: local-postgres-db
    environment:
      POSTGRES_DB: gymcrm_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: myadmin1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: springcore-app
    depends_on:
      - postgres
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: gymcrm_db
      DB_USER: postgres
      DB_PASS: myadmin1234
    ports:
      - "8080:8080"

volumes:
  postgres_data:
