# src/main/resources/application.yaml

data:
  trainers:
    path: classpath:data/trainers.json
  trainees:
    path: classpath:data/trainees.json
  trainings:
    path: classpath:data/trainings.json
  trainingtypes:
    path: classpath:data/trainingTypes.json

#Database configuration
database:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/gymcrmdb
  username: postgres
  password: myadmin1234

#Hibernate configuration
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  packages-to-scan: com.gymcrm.model

#Flyway
flyway:
  locations: classpath:db/migration




